import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Layout({ children, metaTitle, metaDescription }) {
  const router = useRouter();
  const pathName =
    router.pathname === "/" ? "Home" : router.pathname.replace("/", "");

  return (
    <>
      <Head>
        <title>{`${metaTitle || `Create Next App ${pathName}`}`}</title>
        <meta
          name="description"
          content={`${metaDescription || "Generated by create next app"}`}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <p>Layout component</p>
      {children}
      <Footer />
    </>
  );
}
